### ISSUE TITLE
Switch Automated Email Sender

### ISSUE THREAD

**Issue by kyleworkman15** [augustanacsc490spring2019/OSL-Calendar-Web-App#11]
Currently set as acesdispatcher email, need an osl email for automated emails

**Comment by kyleworkman15** [comment]
The new email will have to turn "less secure app access" on:

https://myaccount.google.com/lesssecureapps?pli=1

**Comment by mwardach** [comment]
Emails now sent from "osleventsapp@augustana.edu".
