### ISSUE TITLE
Implement groups for leaders

### ISSUE THREAD

**Issue by kyleworkman15** [augustanacsc490spring2019/OSL-Calendar-Web-App#14]

**Comment by fstonedahl** [comment]
@kyleworkman15 can you elaborate on this?

**Comment by kyleworkman15** [comment]
Allowing admins to add leaders and assign them to specific group(s). That way leaders can only add events for a group that they are attached to.

**Comment by fstonedahl** [comment]
Got it -- yes, I see, right now leaders and groups both **exist** in the realtime database, but there is nothing connecting them.

We either need each leader to have a list of groups that it is a leader of, or we need each group to have a list of leaders.  (Or both.)

**Comment by mwardach** [comment]
Done
