### ISSUE TITLE
Allow Leaders to see their own events in current events so they can do raffles and maybe edit?

### ISSUE THREAD

**Issue by kyleworkman15** [augustanacsc490spring2019/OSL-Calendar-Web-App#17]

**Comment by fstonedahl** [comment]
I think OSL was leaning toward not allowing editing after the event is published, but the raffling (and seeing or downloading a current list of attendees) would be nice for leaders.

**Comment by mwardach** [comment]
Done. Pop-up for leaders nows shows a message saying to send an email to osleventsapp@augustana.edu with their requested change.
