### ISSUE TITLE
Review all API keys / potential security weaknesses?

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Web-App#20]
If any API keys have been leaked publicly, we should probably deactivate those and regenerate new ones that are kept secure.  Or use "service accounts"?

Read up on best practices, to see whether this app (& the Android & iOS apps) are following them...
https://cloud.google.com/docs/authentication/getting-started
https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually

**Comment by fstonedahl** [comment]
See also: https://github.com/AugustanaComputerScienceProjects/Aces-Web-Dispatch/issues/1

**Comment by mwardach** [comment]
Everything seems to be fine.
