### ISSUE TITLE
Upload spreadsheet of leaders/groups?

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Web-App#24]
I picture the OSL would like to be able to do a bulk *upload* of all the leaders/groups at the beginning of each school year.

We should also have an option to clear/delete all leaders, which OSL might want to use before uploading the new year's leaders?

**Comment by fstonedahl** [comment]
Suggested format: (Excel or CSV???)

GroupA, LeaderA1, LeaderA2, ...
GroupB, LeaderB1
GroupC, 
GroupD, LeaderD1

Note, if a group doesn't have any leaders, then still create the group in the database so OSL can create events for them?

**Comment by mwardach** [comment]
Done
