### ISSUE TITLE
Image caching to reduce data usage

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Web-App#31]
https://stackoverflow.com/questions/37699688/cache-images-local-from-google-firebase-storage/40544554

Note: should do something similar for iOS app also.

**Comment by fstonedahl** [comment]
I think Picasso *may* just handle disk caching too now, without any extra work?

https://square.github.io/picasso/#features

**Comment by fstonedahl** [comment]
Actually, I suspect we want to use FirebaseUI for this too.  

_"Images displayed using FirebaseImageLoader are cached by their path in Cloud Storage, so repeated loads will be fast and conserve bandwidth."_  -- https://github.com/firebase/FirebaseUI-Android/tree/master/storage

**Comment by fstonedahl** [comment]
Question: do we want to switch to using FirebaseUI with Glide, or keep using Picasso?  IS PICASSO doing a good job of caching images?  How can we tell?

**Comment by fstonedahl** [comment]
We checked, and Picasso is working on Android.

**Just need to implement image caching on iOS...**

**Comment by mwardach** [comment]
Image caching seems to be working on iOS.
