### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by kyleworkman15** [augustanacsc490spring2019/OSL-Calendar-Web-App#35]

**Comment by fstonedahl** [comment]
Seems like somewhere we should give credit to the team of developers who worked on this project, and maybe include a little "Created by Augie Students for Augie Students" slogan or something... either in a Splash screen, or in an "About" screen.

**Comment by mwardach** [comment]
Note: Android already has a login screen, but it doesn't have a nice logo showing.

**Comment by mwardach** [comment]
Done.
