### ISSUE TITLE
attach (optional) web link to each event

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Web-App#38]
1) Need to add a link field in the web app

2) Need to "More Info!" link or button to each event page in the Android & iOS apps, but ONLY display that IF the event has a non-empty link.

**Comment by fstonedahl** [comment]
Android: https://stackoverflow.com/questions/2734270/how-do-i-make-links-in-a-textview-clickable

**Comment by mwardach** [comment]
Done
