### ISSUE TITLE
email confirmation after accepting pending events is failing?

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Web-App#40]
Investigate this...

**Comment by fstonedahl** [comment]
This appears to have been caused by a Firebase bug after we switched to Node 10, or something?

See: https://github.com/firebase/firebase-functions/issues/447

We can try rolling back to an older Node version for our firebase functions?

**Comment by fstonedahl** [comment]
Also, there was another issue, which was that the password wasn't filled in.

**Comment by fstonedahl** [comment]
The appropriate way to handle email/password info, without inadvertently leaking it into git/GitHub, would be to configure cloud environment variables to store the credentials, and then refer to those from within the cloud function.  See:

https://github.com/firebase/functions-samples/tree/Node-8/email-confirmation
https://github.com/firebase/functions-samples/blob/Node-8/email-confirmation/functions/index.js

**Comment by fstonedahl** [comment]
See also: issue #11

**Comment by mwardach** [comment]
Fixed. Email and Password now stored using Firebase Functions Config.
