### ISSUE TITLE
Demographic database dump from ITS

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Web-App#42]
Need to talk to ITS about this.

Are there any privacy concerns?

Where will we store all the demographic information?  (Separate tree within firebase?)

**Comment by mwardach** [comment]
Upload is working, but to route user to Success page on successful upload of data.

**Comment by mwardach** [comment]
User is now routed to a Success page, displaying a message that the upload was successful.
