### ISSUE TITLE
PepsiCo Special Support!

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Web-App#45]
1. Create a pepsico tree in firebase that will hold the event for each current day
2. Cron job should also check the pepsico tree to see if the single event there has expired, and IF SO, move it to past events also, AND create a new pepsico event for the next day.
3. Need SIMPLE web interface for Pepsico student account that lets the student (or usually cardswipe reader) enter the student ID (or student email) and hit enter, and adds that attendee to the firebase data. 
4. Step 3 above requires linking student ID #s to students emails using data that ITS provides (and updates, so we always have the active list of people on campus.)
5. Also, they want 3 dummy ID cards for: a) alumni, b) guests, and c) specialeventusers (e.g. cardiac rehab group).  (Do we need to have ITS create fake accounts for these, or just handle it all as special cases in our own code?)

**Comment by fstonedahl** [comment]
Need to learn about React "Router".  See:

https://codeburst.io/getting-started-with-react-router-5c978f70df91

**Comment by mwardach** [comment]
Everything done, except point 5, which we will make a new ticket for.
