### ISSUE TITLE
Firebase Date Format

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Web-App#48]
Change Firebase to use ISO standard date/time formatting, so that Firebase query sorting works correctly with it.

SEE: https://stackoverflow.com/questions/37976468/saving-and-retrieving-date-in-firebase

In Java:
```
SimpleDateFormat ISO_8601_FORMAT = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:sss'Z'");
String now = ISO_8601_FORMAT.format(new Date());
```

In Javascript, this ISO standard is accepted in the Date constructor, so just pass it in...
```new Date("2018-03-30T13:18:39.516Z")```

**Comment by fstonedahl** [comment]
Change of plan to use the slightly simpler format: "yyyy-MM-dd HH:mm', which will still sort correctly chronologically.

**Comment by mwardach** [comment]
All done except iOS needs prettier formatting for the dates.

**Comment by mwardach** [comment]
Done.
