### ISSUE TITLE
UI Layout Redo for Mobile Apps

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Web-App#49]
Some ideas (subject to further thought/revision):

Remove Sorting.  
Leave searching (but only start interactively displaying results when they've entered at least 3 characters?)
Move Settings up to a "..." menu?

Bottom Buttons:  All Events (list icon?), My Events (star icon?), Scan In, Show ID (for eventual admin checkin).

**Comment by mwardach** [comment]
Here is some information on how to generate a QR code using the zxing library, which is already implemented in the android app.

https://stackoverflow.com/questions/8800919/how-to-generate-a-qr-code-for-an-android-application

**Comment by mwardach** [comment]
(Hold off on Show ID until we do admin check in later...)

**Comment by mwardach** [comment]
Done. Show ID has been removed from bottom navigation.
