### ISSUE TITLE
Compressing Images

### ISSUE THREAD

**Issue by kyleworkman15** [augustanacsc490spring2019/OSL-Calendar-Web-App#5]

**Comment by fstonedahl** [comment]
Do you mean resizing (downsampling) images that get uploaded, so they take up less space and bandwidth?

**Comment by kyleworkman15** [comment]
Yes. If an image is uploaded in quad HD or some high resolution, I think the image should be downsampled to a certain resolution.

**Comment by mwardach** [comment]
Sounds good - at the same time we may also want to convert the data so it's really in JPG format even if they uploaded a GIF or PNG image.

**Comment by mwardach** [comment]
Resize images to 500 by 500 before upload.
